CREATE DATABASE projetClassroom CHARSET utf8mb4;
USE projetClassroom;

CREATE TABLE `user`(
id_user INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
firstname VARCHAR(50) NOT NULL,
lastname VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL UNIQUE,
`password` VARCHAR(100) NOT NULL
)ENGINE = InnoDB;